region: London
geohash_precision: 8

crs:
  meters: epsg:27700
  latlon_gps: epsg:4326
  latlon_osgb: epsg:4277
  proj_os32: +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs

paths:
  area_polygon: "../MAPPING DATA/Master_Area_Map/Master_Area_Map.TAB"
  save_as: "geohash_polygons"
